title: Andrew Cheng
description: "I'm a guy that builds stuff to solve problems"
url: https://andrew-cheng.com
baseurl: ""
permalink: pretty
collections:
  projects:
    output: false
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - node_modules
  - dist
  - src
  - scripts
